# Generated by Django 2.2 on 2020-11-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_construction_system', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_origin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_potential_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_standard', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_project', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_use', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_useful_life', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255)),
                ('builded_surface', models.IntegerField()),
                ('living_area', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Country')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.TypeProject')),
                ('use_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Use')),
                ('useful_life_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.UsefulLife')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSchemeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('provider_distance', models.DecimalField(decimal_places=10, max_digits=15)),
                ('construction_system_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.ConstructionSystem')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Material')),
                ('origin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Origin')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Project')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Section')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSchemeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=15)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Material')),
                ('potential_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.PotentialType')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Standard')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit')),
            ],
        ),
    ]
