# Generated by Django 2.2 on 2020-10-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemedata',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='provider_distance',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.CreateModel(
            name='MaterialProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_impact_value', models.DecimalField(decimal_places=10, max_digits=15)),
                ('material_scheme_data_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.MaterialSchemeData')),
                ('material_scheme_project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.MaterialSchemeProject')),
            ],
        ),
    ]
