# Generated by Django 2.2 on 2020-11-07 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_housing_scheme', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='housung_scheme_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.HousingScheme'),
        ),
    ]
