# Generated by Django 2.2 on 2020-11-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0002_auto_20201106_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='housung_scheme_id',
            new_name='housing_scheme_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.TypeProject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Use'),
        ),
        migrations.AlterField(
            model_name='project',
            name='useful_life_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.UsefulLife'),
        ),
    ]
