# Generated by Django 2.2 on 2020-11-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0003_auto_20201106_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemedata',
            name='material_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Material'),
        ),
        migrations.AlterField(
            model_name='materialschemedata',
            name='potential_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.PotentialType'),
        ),
        migrations.AlterField(
            model_name='materialschemedata',
            name='standard_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Standard'),
        ),
        migrations.AlterField(
            model_name='materialschemedata',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='construction_system_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.ConstructionSystem'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='material_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Material'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='origin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Origin'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Project'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Section'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit'),
        ),
    ]
