# Generated by Django 2.2 on 2020-11-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0004_auto_20201106_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialschemeproject',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='material',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit'),
        ),
    ]
