# Generated by Django 2.2 on 2020-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0005_auto_20201107_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialschemeproject',
            name='construction_system_id',
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='construction_system',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ConstructionSystem',
        ),
    ]
