# Generated by Django 2.2 on 2020-11-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0006_auto_20201109_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_volume_unit', models.CharField(max_length=255)),
            ],
        ),
    ]
