# Generated by Django 2.2 on 2020-11-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0008_energyunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bulk_unit', models.CharField(max_length=255)),
            ],
        ),
    ]
