# Generated by Django 2.2 on 2020-11-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0009_bulkunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_source_information', models.CharField(max_length=255)),
            ],
        ),
    ]
