# Generated by Django 2.2 on 2020-11-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0010_sourceinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructiveProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_constructive_process', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructiveSystemElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bulk_unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.BulkUnit')),
                ('constructive_process_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.ConstructiveProcess')),
                ('energy_unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.EnergyUnit')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Project')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Section')),
                ('source_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.SourceInformation')),
                ('volume_unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.VolumeUnit')),
            ],
        ),
    ]
