# Generated by Django 2.2 on 2020-11-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0011_constructiveprocess_constructivesystemelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructivesystemelement',
            old_name='source_information',
            new_name='source_information_id',
        ),
    ]
