# Generated by Django 2.2 on 2020-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0012_auto_20201111_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionStageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_construction_stage_type', models.CharField(max_length=255)),
            ],
        ),
    ]
