# Generated by Django 2.2 on 2020-11-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0013_constructionstagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructivesystemelement',
            name='construction_stage_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.ConstructionStageType'),
        ),
    ]
