# Generated by Django 2.2 on 2020-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0017_electricityconsumptiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemedata',
            name='value',
            field=models.DecimalField(decimal_places=100, max_digits=150),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='provider_distance',
            field=models.DecimalField(decimal_places=100, max_digits=150),
        ),
    ]
