# Generated by Django 2.2 on 2020-11-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0018_auto_20201126_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemedata',
            name='value',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='provider_distance',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
    ]
