# Generated by Django 2.2 on 2020-12-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0019_auto_20201130_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialschemeproject',
            name='provider_distance',
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='value',
            field=models.DecimalField(decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='materialschemedata',
            name='value',
            field=models.DecimalField(decimal_places=25, max_digits=25, null=True),
        ),
        migrations.CreateModel(
            name='StageSchemeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stage', models.CharField(max_length=255, null=True)),
                ('abbreviation', models.CharField(max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=25, max_digits=25, null=True)),
                ('stage', models.CharField(max_length=255, null=True)),
                ('unit_stage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit')),
            ],
        ),
    ]
