# Generated by Django 2.2 on 2020-12-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0020_auto_20201202_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_energy', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='electricityconsumptiondata',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.TypeEnergy'),
        ),
    ]
