# Generated by Django 2.2 on 2020-12-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0021_auto_20201202_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialschemeproject',
            name='provider_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
