# Generated by Django 2.2 on 2020-12-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0027_treatmentofgeneratedwaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemedata',
            name='value',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='value',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
        migrations.AlterField(
            model_name='stageschemedata',
            name='value',
            field=models.DecimalField(decimal_places=23, max_digits=45, null=True),
        ),
        migrations.CreateModel(
            name='SourceInformationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=35, max_digits=45, null=True)),
                ('potential_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.PotentialType')),
                ('sourceInformarion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.SourceInformation')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects_api.Unit')),
            ],
        ),
    ]
