# Generated by Django 2.2 on 2020-12-18 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0029_typeenergydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='housing_scheme_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.HousingScheme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.TypeProject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Use'),
        ),
        migrations.AlterField(
            model_name='project',
            name='useful_life_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.UsefulLife'),
        ),
    ]
