# Generated by Django 2.2 on 2021-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0031_auto_20201217_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
