# Generated by Django 2.2 on 2021-01-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0034_project_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
