# Generated by Django 2.2 on 2021-01-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0035_auto_20210112_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms',
        ),
    ]
