# Generated by Django 2.2 on 2021-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0036_auto_20210112_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pais',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='information',
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
