# Generated by Django 2.2 on 2021-01-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0037_auto_20210112_0253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserPlatform',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user_platform_id',
        ),
    ]
