# Generated by Django 2.2 on 2021-01-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0041_electricityconsumptiondata_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255)),
                ('builded_surface', models.IntegerField(null=True)),
                ('living_area', models.IntegerField(null=True)),
                ('tier', models.IntegerField(null=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Country')),
                ('housing_scheme_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.HousingScheme')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.TypeProject')),
                ('use_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Use')),
                ('useful_life_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.UsefulLife')),
                ('user_platform_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.UserPlatform')),
            ],
        ),
    ]
