# Generated by Django 2.2 on 2021-01-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0042_projectoriginal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSchemeProjectOrigianal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_system', models.CharField(max_length=255, null=True)),
                ('provider_distance', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('value', models.DecimalField(decimal_places=35, max_digits=45, null=True)),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Material')),
                ('origin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Origin')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Project')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Section')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectOriginal',
        ),
    ]
