# Generated by Django 2.2 on 2021-01-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0046_localdistance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localdistance',
            old_name='city_id',
            new_name='city_id_origin',
        ),
        migrations.AddField(
            model_name='localdistance',
            name='city_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localdistance_requests_created', to='projects_api.City'),
        ),
    ]
