# Generated by Django 2.2 on 2021-01-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0047_auto_20210125_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='citi_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_requests_created', to='projects_api.City'),
        ),
        migrations.AddField(
            model_name='project',
            name='city_id_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.City'),
        ),
        migrations.AddField(
            model_name='project',
            name='distance',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
    ]
