# Generated by Django 2.2 on 2021-01-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0048_auto_20210126_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialschemeproject',
            name='distanceEnd',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='distanceInit',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='materialschemeprojectorigianal',
            name='distanceEnd',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='materialschemeprojectorigianal',
            name='distanceInit',
            field=models.DecimalField(decimal_places=35, max_digits=45, null=True),
        ),
    ]
