# Generated by Django 2.2 on 2021-02-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0049_auto_20210129_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=35, max_digits=45, null=True)),
                ('country_id_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Country')),
            ],
        ),
    ]
