# Generated by Django 2.2 on 2021-02-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0051_materialschemeproject_replaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='citi_id_end',
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='citi_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialschemeproject_requests_created', to='projects_api.City'),
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='city_id_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.City'),
        ),
    ]
