# Generated by Django 2.2 on 2021-02-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0055_auto_20210217_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_transport', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='transport_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialschemeproject_requests_created_second', to='projects_api.Transport'),
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='transport_id_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Transport'),
        ),
        migrations.AddField(
            model_name='materialschemeprojectorigianal',
            name='transport_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialschemeprojectorigianal_requests_created_second', to='projects_api.Transport'),
        ),
        migrations.AddField(
            model_name='materialschemeprojectorigianal',
            name='transport_id_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Transport'),
        ),
    ]
