# Generated by Django 2.2 on 2021-02-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0056_auto_20210218_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldistance',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
