# Generated by Django 2.2 on 2021-04-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0057_externaldistance_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialtype',
            name='name_complete_potential_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='potentialtype',
            name='name_potential_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
