# Generated by Django 2.2 on 2021-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0058_auto_20210409_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialtype',
            name='unit_potential_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
