# Generated by Django 2.2 on 2021-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0059_potentialtype_unit_potential_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialschemeproject',
            name='description_material',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialschemeproject',
            name='unit_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
