# Generated by Django 2.2 on 2021-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0061_materialschemeproject_state_id_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='database_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name_material',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
