# Generated by Django 2.2 on 2021-07-05 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0062_auto_20210629_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('airport', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.CharField(max_length=255, null=True)),
                ('departure_date', models.CharField(max_length=255, null=True)),
                ('cost', models.CharField(max_length=255, null=True)),
                ('arrival_airport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flightcosts_requests_created', to='projects_api.Airports')),
                ('departure_airport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Airports')),
            ],
        ),
    ]
