# Generated by Django 2.2 on 2021-07-05 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0063_airports_flightcosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcosts',
            name='arrival_airport_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flightcosts_requests_created_unique', to='projects_api.Airports'),
        ),
    ]
