# Generated by Django 2.2 on 2021-07-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0064_auto_20210704_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.CharField(max_length=255, null=True)),
                ('departureDate', models.CharField(max_length=255, null=True)),
                ('cost', models.CharField(max_length=255, null=True)),
                ('img', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='airports',
            old_name='country_code',
            new_name='countryCode',
        ),
        migrations.DeleteModel(
            name='FlightCosts',
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrivalAirportId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flightinfo_requests_created_unique', to='projects_api.Airports'),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departureAirportId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Airports'),
        ),
    ]
