# Generated by Django 2.2 on 2021-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0065_auto_20210705_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
