# Generated by Django 2.2 on 2021-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0066_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemeproject',
            name='description_material',
            field=models.TextField(null=True),
        ),
    ]
