# Generated by Django 2.2 on 2021-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0067_auto_20210901_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemeproject',
            name='transport_id_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='transport_id_origin',
            field=models.IntegerField(null=True),
        ),
    ]
