# Generated by Django 2.2 on 2021-09-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0068_auto_20210909_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemeproject',
            name='description_material',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='transport_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialschemeproject_requests_created_second', to='projects_api.Transport'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='transport_id_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Transport'),
        ),
    ]
