# Generated by Django 2.2 on 2021-12-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0069_auto_20210909_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemeproject',
            name='description_material',
            field=models.TextField(null=True),
        ),
    ]
