# Generated by Django 2.2 on 2022-01-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0072_auto_20220116_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=35, max_digits=45, null=True)),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Material')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=35, max_digits=45, null=True)),
                ('potential_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.PotentialType')),
                ('transport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Transport')),
            ],
        ),
        migrations.RemoveField(
            model_name='flightinfo',
            name='arrivalAirportId',
        ),
        migrations.RemoveField(
            model_name='flightinfo',
            name='departureAirportId',
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.DeleteModel(
            name='FlightInfo',
        ),
    ]
