# Generated by Django 2.2 on 2022-02-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0073_auto_20220125_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_standard', models.CharField(max_length=255)),
            ],
        ),
    ]
