# Generated by Django 2.2 on 2022-02-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0074_databasematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasematerial',
            old_name='name_standard',
            new_name='name',
        ),
    ]
