# Generated by Django 2.2 on 2022-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0075_auto_20220213_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialschemeproject',
            name='quantity',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
